### ISSUE TITLE
Delete default values for 64bit unsigns

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/ipInterface#2]
The uml currently defines unsign integers with default value -1, but -1 is not unsigned. Therefore the default value should be deleted from uml.

The request refers to - Note: UML-to-yang currently generates for all mentioned integers a uint64, even if the length 32 is set in the profile - please remove default values only if it makes sense. 

CurrentPerformance/elapsedTime
IpInterfaceCapability/maximumNumberOfIpV4Addresses
IpInterfaceCapability/maximumTransmissionUnitMax
IpInterfaceCapability/maximumTransmissionUnitMin
IpInterfaceCapability/informationRateMin
IpInterfaceCapability/informationRateMax
IpInterfaceCapability/burstSizeMin
IpInterfaceCapability/burstSizeMax
IpInterfaceConfiguration/maximumTransmissionUnitIp
IpInterfaceConfiguration/maximumInformationRate
IpInterfaceConfiguration/maximumBurstSize
IpInterfaceConfiguration/maintenanceTimer

IpV4AddressType/fixedIpV4AddressPrefixLength (question: better ietf-inet-types:ipv4-prefix?)
IpInterfacePerformance-type/last10SecDataInputRate
IpInterfacePerformance-type/last10SecDataOuputRate
IpInterfacePerformance-type/last10SecPacketInputRate
IpInterfacePerformance-type/last10SecPacketOutputRate
IpInterfacePerformance-type/dataVolumeInput
IpInterfacePerformance-type/dataVolumeOutput
IpInterfacePerformance-type/totalPacketsInput
IpInterfacePerformance-type/totalPacketsOutput
IpInterfacePerformance-type/forwardedDataVolumeInput
IpInterfacePerformance-type/forwardedDataVolumeOutput
IpInterfacePerformance-type/forwardedPacketsInput
IpInterfacePerformance-type/forwardedPacketsOutput
IpInterfacePerformance-type/unicastPacketsInput
IpInterfacePerformance-type/unicastPacketsOutput
IpInterfacePerformance-type/multicastPacketsInput
IpInterfacePerformance-type/multicastPacketsOutput
IpInterfacePerformance-type/broadcastPacketsInput
IpInterfacePerformance-type/broadcastPacketsOutput
IpInterfacePerformance-type/fragmentedPacketsInput
IpInterfacePerformance-type/fragmentedPacketsOutput
IpInterfacePerformance-type/erroredPacketsInput
IpInterfacePerformance-type/erroredPacketsOutput
IpInterfacePerformance-type/droppedPacketsInput
IpInterfacePerformance-type/droppedPacketsOutput

(internal note: email from 2019-05-21 with subject IpInterface)
(checking why "unit" and "integer-length" is currenly ignored by uml-to-yang...)

**Comment by openBackhaul** [comment]
Actually the UML currently defines:

- CurrentPerformance/elapsedTime deleted

- IpInterfaceCapability/maximumNumberOfIpV4Addresses 16Bit signed
- IpInterfaceCapability/maximumTransmissionUnitMax 16bit signed
- IpInterfaceCapability/maximumTransmissionUnitMin 16bit signed
- IpInterfaceCapability/informationRateMin 32bit signed
- IpInterfaceCapability/informationRateMax 32bit signed
- IpInterfaceCapability/burstSizeMin 16bit signed
- IpInterfaceCapability/burstSizeMax 16bit signed
- IpInterfaceConfiguration/maximumTransmissionUnitIp 16bit signed
- IpInterfaceConfiguration/maximumInformationRate  32bit signed
- IpInterfaceConfiguration/maximumBurstSize 16bit signed
- IpInterfaceConfiguration/maintenanceTimer 32bit signed

- IpV4AddressType/fixedIpV4AddressPrefixLength 8Bit signed

- IpInterfaceStatus/last10SecDataInputRate 32bit signed
- IpInterfaceStatus/last10SecDataOuputRate 32bit signed
- IpInterfaceStatus/last10SecPacketInputRate 32bit signed
- IpInterfaceStatus/last10SecPacketOutputRate 32bit signed
- IpInterfaceStatus/dataVolumeInput 32bit signed
- IpInterfaceStatus/dataVolumeOutput 32bit signed
- IpInterfaceStatus/totalPacketsInput 64bit signed
- IpInterfaceStatus/totalPacketsOutput 64bit signed
- IpInterfaceStatus/forwardedDataVolumeInput 32bit signed
- IpInterfaceStatus/forwardedDataVolumeOutput 32bit signed
- IpInterfaceStatus/forwardedPacketsInput 64bit signed
- IpInterfaceStatus/forwardedPacketsOutput 64bit signed
- IpInterfaceStatus/unicastPacketsInput 64bit signed
- IpInterfaceStatus/unicastPacketsOutput 64bit signed
- IpInterfaceStatus/multicastPacketsInput 32bit signed
- IpInterfaceStatus/multicastPacketsOutput 32bit signed
- IpInterfaceStatus/broadcastPacketsInput 32bit signed
- IpInterfaceStatus/broadcastPacketsOutput 32bit signed
- IpInterfaceStatus/fragmentedPacketsInput 32bit signed
- IpInterfaceStatus/fragmentedPacketsOutput 32bit signed
- IpInterfaceStatus/erroredPacketsInput 32bit signed
- IpInterfaceStatus/erroredPacketsOutput 32bit signed
- IpInterfaceStatus/droppedPacketsInput 32bit signed
- IpInterfaceStatus/droppedPacketsOutput 32bit signed

=> No negative default value is colliding with unsigned integer in UML.

Checked the default values.
=> Would prefer keeping the current "-1" values in accordiance with other models.
